/* Generated by Cython 0.29.14 */

#ifndef __PYX_HAVE__C_ia_potential_alignments
#define __PYX_HAVE__C_ia_potential_alignments

#include "Python.h"

#ifndef __PYX_HAVE_API__C_ia_potential_alignments

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C int MATRIX_COEFFS[7];

#endif /* !__PYX_HAVE_API__C_ia_potential_alignments */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initC_ia_potential_alignments(void);
#else
PyMODINIT_FUNC PyInit_C_ia_potential_alignments(void);
#endif

#endif /* !__PYX_HAVE__C_ia_potential_alignments */
